name: "Test chromedriver on *NIX"
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    branches:
      - '*'
    paths:
      - '**'
      - '!*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2
    - if: matrix.os == 'ubuntu-latest'
      run: echo 'CHROMEAPP=google-chrome' >> $GITHUB_ENV
    - if: matrix.os == 'macos-latest'
      run: echo 'CHROMEAPP=/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' >> $GITHUB_ENV
    - run: rm -rf node_modules && yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
    - run: |
        CHROME_VERSION=$("$CHROMEAPP" --version | cut -f 3 -d ' ' | cut -d '.' -f 1)
        echo "CHROMEDRIVER_VERSION=$(curl --location --fail --retry 10 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})" >> $GITHUB_ENV
    - uses: ./
      with:
        chromedriver-version: ${{ env.CHROMEDRIVER_VERSION }}
    - name: setup
      run: |
        sudo pip3 install selenium
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # disable headless mode
        python3 $GITHUB_WORKSPACE/__tests__/chromedriver.py

  test_default_version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2
    - if: matrix.os == 'ubuntu-latest'
      run: echo 'CHROMEAPP=google-chrome' >> $GITHUB_ENV
    - if: matrix.os == 'macos-latest'
      run: echo 'CHROMEAPP=/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' >> $GITHUB_ENV
    - run: rm -rf node_modules && yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
    - uses: ./
    - name: setup
      run: |
        "$CHROMEAPP" --version
        sudo pip3 install selenium
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # disable headless mode
        python3 $GITHUB_WORKSPACE/__tests__/chromedriver.py
